# Generated by Django 5.1.7 on 2025-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('risk_tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('income_stability', models.CharField(blank=True, max_length=50, null=True)),
                ('income_sources', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_horizon', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_return', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_loss', models.CharField(blank=True, max_length=50, null=True)),
                ('investment_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
