# Generated by Django 5.1.7 on 2025-03-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_investmentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='monthly_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
