# Generated by Django 4.2.20 on 2025-05-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_investmentprofile_monthly_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='InvestmentProfile',
        ),
    ]
