# Generated by Django 4.2.20 on 2025-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_investmentprofile_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='asset_allocation_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='investment_concern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='risk_acceptance_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='value_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
