# Generated by Django 4.2.20 on 2025-06-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_chatmessage_delete_investmentprofile'),
        ('chat', '0004_investmentprofile_asset_allocation_type_and_more'),
    ]

    operations = [
    ]
