# Generated by Django 4.2.23 on 2025-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_merge_20250618_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('risk_tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('income_stability', models.CharField(blank=True, max_length=50, null=True)),
                ('income_sources', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('investment_horizon', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_return', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_loss', models.CharField(blank=True, max_length=50, null=True)),
                ('investment_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_allocation_type', models.IntegerField(blank=True, null=True)),
                ('value_growth', models.IntegerField(blank=True, null=True)),
                ('risk_acceptance_level', models.IntegerField(blank=True, null=True)),
                ('investment_concern', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'user_id'], name='chat_invest_session_e9a730_idx')],
                'unique_together': {('session_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('product_type', models.CharField(blank=True, choices=[('stock', '주식'), ('deposit', '예금'), ('saving', '적금'), ('annuity', '연금')], max_length=20, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'timestamp'], name='chat_chatme_session_e81882_idx'), models.Index(fields=['username', 'timestamp'], name='chat_chatme_usernam_416800_idx')],
            },
        ),
    ]
