# Generated by Django 4.2.23 on 2025-08-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentProfile',
        ),
    ]
