version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cd naughtyDjango && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: naughtyDjango.settings  # .py는 생략
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  dbdata:
  static_volume:
  media_volume: