# Generated by Django 4.2.23 on 2025-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annuity',
            fields=[
                ('avg_prft_rate', models.FloatField(blank=True, null=True)),
                ('btrm_prft_rate1', models.FloatField(blank=True, null=True)),
                ('guar_rate', models.FloatField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('pnsn_kind_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('prdt_type_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_co', models.TextField(blank=True, null=True)),
                ('sale_strt_day', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'annuity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etc_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('mtrt_int', models.CharField(blank=True, max_length=1000, null=True)),
                ('spcl_cnd', models.CharField(blank=True, max_length=1000, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'deposit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like_num', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostScrap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'post_scrap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etc_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('mtrt_int', models.CharField(blank=True, max_length=1000, null=True)),
                ('spcl_cnd', models.CharField(blank=True, max_length=1000, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('join_member', models.CharField(blank=True, max_length=255, null=True)),
                ('join_way', models.CharField(blank=True, max_length=255, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'savings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('social_type', models.IntegerField(blank=True, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_income', models.BigIntegerField(blank=True, null=True)),
                ('expected_loss', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('income', models.BigIntegerField(blank=True, null=True)),
                ('period', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_situation', models.CharField(blank=True, max_length=255, null=True)),
                ('income_source', models.CharField(blank=True, max_length=255, null=True)),
                ('income_stability', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_proportion', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_tolerance', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_allocation_type', models.IntegerField(blank=True, null=True)),
                ('value_growth', models.IntegerField(blank=True, null=True)),
                ('risk_acceptance_level', models.IntegerField(blank=True, null=True)),
                ('investment_concern', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
                'indexes': [models.Index(fields=['email'], name='user_email_7bbb4c_idx'), models.Index(fields=['nickname'], name='user_nicknam_c84b97_idx'), models.Index(fields=['created_at'], name='user_created_855a50_idx'), models.Index(fields=['updated_at'], name='user_updated_187a57_idx'), models.Index(fields=['risk_tolerance'], name='user_risk_to_d33aed_idx'), models.Index(fields=['asset_allocation_type'], name='user_asset_a_e7aa94_idx'), models.Index(fields=['value_growth'], name='user_value_g_7d63d4_idx'), models.Index(fields=['risk_acceptance_level'], name='user_risk_ac_545759_idx'), models.Index(fields=['investment_concern'], name='user_investm_ea837d_idx'), models.Index(fields=['risk_tolerance', 'risk_acceptance_level'], name='user_risk_to_9b9822_idx'), models.Index(fields=['asset_allocation_type', 'value_growth'], name='user_asset_a_f070bd_idx')],
            },
        ),
    ]
